name: 'Run Nox Session'
description: 'Action to run a nox session'
inputs:
  python_version:
    required: true
    type: string
    description: "python version to install for nox"
  nox_session:
    required: true
    type: string
    description: "name of the nox session to run"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      # Do not run if no sessions (for example nox reuse_virtualenv)
      if:  ${{ inputs.python_version != '' }}
      with:
        python-version: ${{ inputs.python_version }}
        cache: "poetry"
        # Install python version for nox environment but do not change default one
        update-environment: false
    - name: Escape characters from ${{ inputs.nox_session }}
      run: echo "${{ inputs.nox_session }}" | sed "s/[,'~()\. =]/_/g" | awk '{print "nox_session_escape="$1}' >> $GITHUB_ENV
      shell: bash
    - name: Cache .nox envdir
      uses: actions/cache@v3
      id: cache
      with:
        path: .nox
        key: nox-envdir-${{ runner.os }}-session-${{ env.nox_session_escape }}
    - run: poetry run nox --session "${{ inputs.nox_session }}" --reuse-existing-virtualenvs
      shell: bash
