name: Bump version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Semver type of new version (major / minor / patch)"
        required: true
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.actor == 'Wirg'
    steps:
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: ./.github/workflows/actions/install_dependencies
        with:
          python-version: "3.9"
          poetry-version: "1.1.10"
          tqdm-version: ""
          streamlit-version: ""

      - name: Setup Git
        run: |
          git config user.name "Wirg"
          git config user.email "Wirg@users.noreply.github.com"

      - name: bump version
        run: poetry version ${{ github.event.inputs.version }}

      - name: create new version
        run: |
          export RELEASE="v$(poetry version --short)"
          export BRANCH="release/${RELEASE}"
          git checkout -b $BRANCH
          git commit -am "bump to version ${RELEASE}"
          git push origin $BRANCH -f
          gh pr create --title "[Release] ${RELEASE} => releases" --body "" --reviewer Wirg --assignee Wirg --head $BRANCH --base releases
          gh pr create --title "[Release] ${RELEASE} => main" --body "" --reviewer Wirg --assignee Wirg --head $BRANCH --base main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
