on:
  push:
    tags:
      - "v*"

name: Create Release

jobs:
  create-github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    name: Publish to pypi
    runs-on: ubuntu-latest
    needs: create-github-release
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/install_dependencies
        with:
          python-version: "3.9"
          poetry-version: "1.1.10"
          tqdm-version: ""
          streamlit-version: ""

      - name: Build
        run: poetry -n build

      - name: Upload artifacts
        run: |
          gh release upload ${{ github.ref }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: poetry -n publish --username __token__ --password ${{ secrets.PYPI_TOKEN }}
