name: Create Release

on:
  push:
    tags:
      - 'v*'
    branch:
      - main

jobs:
  create-release-build-and-publish:
    environment: publish
    name: Create Release, Build & Publish to pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/actions/install_dependencies

      - name: export release-data
        id: release-data
        run: |
          export RELEASE="v$(poetry version --short)"
          echo "version=${RELEASE}" >> $GITHUB_OUTPUT

      - name: Build
        run: poetry build -n

      - name: Check Version
        id: check-prerelease
        run: |
          [[ "$(poetry version --short)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || echo prerelease_flag="--prerelease" >> $GITHUB_OUTPUT

      - name: Create Release
        run: gh release create ${{ steps.release-data.outputs.version }} --generate-notes ${{ steps.check-prerelease.outputs.prerelease_flag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        run: |
          gh release upload ${{ steps.release-data.outputs.version }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish
        run: poetry publish -n --username __token__ --password ${{ secrets.PYPI_TOKEN }}
