name: Scorecard

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8 * * 1"

jobs:
  analysis:
    name: OSSF Scorecard
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Run Scorecard
        uses: ossf/scorecard-action@v2.4.3
        with:
          repo_token: ${{ github.token }}
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload to code scanning
        uses: github/codeql-action/upload-sarif@68bde559dea0fdcac2102bfdf6230c5f70eb485e # v4.35.4
        with:
          sarif_file: scorecard.sarif
