name: 'Install Dependencies'
description: 'Action to build the project dependencies from the main versions'
inputs:
  python_version:
    required: true
    type: string
    default: "3.12"

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python_version }}
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install Dependencies
      run: uv sync --locked --all-groups
      shell: bash
