name: 'Install Dependencies'
description: 'Action to build the project dependencies from the main versions'
inputs:
  python_version:
    required: true
    type: string
    default: "3.9"
  poetry_version:
    required: true
    type: string
    default: "1.3.1"

runs:
  using: composite
  steps:
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry_version }}
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python_version }}
        cache: "poetry"
    - name: Install Dependencies
      run: poetry --no-interaction --no-cache install --no-root --with nox --with dev
      shell: bash
