name: 'Install Dependencies'
description: 'Action to build the project dependencies from the main versions'
inputs:
  python-version:
    required: true
    type: string
    default: "3.9"
  tqdm-version:
    required: true
    type: string
    default: ""
  streamlit-version:
    required: true
    type: string
    default: ""
  poetry-version:
    required: true
    type: string
    default: "1.2.1"

runs:
  using: composite
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Upgrade pip
      run: python3 -m pip install --upgrade pip
      shell: bash
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: false
        virtualenvs-in-project: false
        installer-parallel: true

    - name: Cache Venv
      uses: actions/cache@v2
      id: cache
      with:
        path: ~/.venv
        key: venv-cache-${{ runner.os }}-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-${{ hashFiles('**/poetry.lock') }}-tqdm-${{ inputs.tqdm-version }}-streamlit-${{ inputs.streamlit-version }}
        restore-keys: |
          venv-cache-${{ runner.os }}-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-${{ hashFiles('**/poetry.lock') }}-tqdm-${{ inputs.tqdm-version }}-streamlit-
          venv-cache-${{ runner.os }}-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-${{ hashFiles('**/poetry.lock') }}-tqdm-
          venv-cache-${{ runner.os }}-${{ inputs.python-version }}-poetry-${{ inputs.poetry-version }}-

    - name: Pip & pypoetry Cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/
        key: ${{ runner.os }}-pip
        restore-keys: ${{ runner.os }}-pip
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Install Venv
      run: python3 -m venv ~/.venv
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
    - name: Install dependencies
      run: |
        source ~/.venv/bin/activate
        poetry install --no-interaction --no-root
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
    - name: Add specific build dependencies
      run: |
        source ~/.venv/bin/activate
        pip install tqdm${{ inputs.tqdm-version }} streamlit${{ inputs.streamlit-version }}
      shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
